palette:
  - "#00bfff" # blue
  - "#ffd700" # gold
  - "#ff6347" # tomato
  - "#adff2f" # greenyellow
  - "#ff69b4" # hotpink
background: "#181825"
snake:
  color: "#00bfff"
  head: "circle"
  tail: "circle" 